# generated by datamodel-codegen:
#   filename:  msgspec_union_normalization.json

from __future__ import annotations

from typing import Annotated

from msgspec import UNSET, Meta, Struct, UnsetType

type Offset = tuple[float, float]


type DeviceType1 = Annotated[str, Meta(pattern='^[a-z0-9_]+$')]


class Item(Struct):
    id: str
    offset: Offset | None | UnsetType = UNSET
    url: str | None | UnsetType = UNSET
    created_at: str | UnsetType = UNSET
    device_type: DeviceType1 | None | UnsetType = UNSET


class DeviceType(Struct):
    name: str


class DeviceTypeList(Struct):
    device_types: list[DeviceType]
