# generated by datamodel-codegen:
#   filename:  msgspec_fixed_tuple_length.json

from __future__ import annotations

from typing import Annotated

from msgspec import UNSET, Meta, Struct, UnsetType

type Offset = tuple[float, float]


class Item(Struct):
    offset: Offset | None | UnsetType = UNSET
    pair: tuple[str, int] | UnsetType = UNSET
    tags: Annotated[list[str], Meta(max_length=3, min_length=1)] | UnsetType = UNSET
