# generated by datamodel-codegen:
#   filename:  msgspec_str_like_unions.json

from __future__ import annotations

from typing import Annotated
from uuid import UUID

from msgspec import UNSET, Meta, Struct, UnsetType

type Slug = Annotated[str, Meta(pattern='^[a-z]+$')]


class Item(Struct):
    id: str
    plain_id: UUID | UnsetType = UNSET
    optional_id: UUID | None | UnsetType = UNSET
    one_of_id: str | UnsetType = UNSET
    ids: list[str] | UnsetType = UNSET
    url: str | None | UnsetType = UNSET
    mixed: str | int | UnsetType = UNSET
    shared: str | UnsetType = UNSET
