# generated by datamodel-codegen:
#   filename:  msgspec_union_normalization.json

from __future__ import annotations

from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, constr


class Item(BaseModel):
    id: UUID | str
    offset: tuple[float, float] | None = None
    url: AnyUrl | constr(max_length=0) | None = None
    created_at: AwareDatetime | None = None
    device_type: constr(pattern=r'^[a-z0-9_]+$') | None = None


class DeviceType(BaseModel):
    name: str


class DeviceTypeList(BaseModel):
    device_types: list[DeviceType]
