# generated by datamodel-codegen:
#   filename:  msgspec_union_normalization.json

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class Item:
    id: str
    offset: tuple[float, float] | None = None
    url: str | None = None
    created_at: str | None = None
    device_type: str | None = None


@dataclass
class DeviceType:
    name: str


@dataclass
class DeviceTypeList:
    device_types: list[DeviceType]
