# generated by datamodel-codegen:
#   filename:  primary_first_inline_alias.json

from __future__ import annotations

from pydantic import BaseModel, Field, RootModel


class DeviceType1(RootModel[str]):
    root: str = Field(..., pattern='^[a-z0-9_]+$')


class Item(BaseModel):
    device_type: DeviceType1 | None = None


class DeviceType(BaseModel):
    name: str


class DeviceTypeList(BaseModel):
    device_types: list[DeviceType]
