# generated by datamodel-codegen:
#   filename:  primary_first_inline_alias.json

from __future__ import annotations

from dataclasses import dataclass

type DeviceType1 = str


@dataclass
class Item:
    device_type: DeviceType1 | None = None


@dataclass
class DeviceType:
    name: str


@dataclass
class DeviceTypeList:
    device_types: list[DeviceType]
