# generated by datamodel-codegen:
#   filename:  primary_first_inline_alias.json

from __future__ import annotations

from typing import Annotated

from msgspec import UNSET, Meta, Struct, UnsetType

type DeviceType1 = Annotated[str, Meta(pattern='^[a-z0-9_]+$')]


class Item(Struct):
    device_type: DeviceType1 | None | UnsetType = UNSET


class DeviceType(Struct):
    name: str


class DeviceTypeList(Struct):
    device_types: list[DeviceType]
